name: Janus
version: '${minecraft.plugin.version}'
api-version: 1.14
description: The plugin portion of the Elastic Teleport Suite.
author: md_5
authors: [Phoenix616]
website: https://github.com/Minebench/Janus

main: net.md_5.janus.Main

commands:
   janus:
      description: Main Janus command.
      usage: /janus reload|info
      permission: janus.command
      permission-message: You don't have the permission to execute this command

permissions:
   janus.sign:
      description: Gives access to the server signs
      default: op
   janus.use:
      description: Gives access to the server portals
      default: true
   janus.use.*:
      description: Gives access to all the server portals
      default: op
   janus.bypass:
      description: Gives access to bypass the cooldown
      default: op
   janus.command:
      description: Gives access to the janus command
      default: op
