name: Janus
version: '${minecraft.plugin.version}'
description: The plugin portion of the Elastic Teleport Suite.
author: md_5
authors: [Phoenix616]
website: https://github.com/Phoenix616/Janus

main: net.md_5.janus.Main

permissions:
   janus.sign:
      description: Gives access to the server signs
      default: op
   janus.use:
      description: Gives access to the server portals
      default: op
